"""Add file and template tables

Revision ID: cb61f85c3622
Revises: 742d5bfb9e6f
Create Date: 2025-12-04 00:36:29.277129

IMPORTANT DOWNGRADE LIMITATION:
This migration converts m_user.created_at and m_user.updated_at from
timezone-aware TIMESTAMP to naive DateTime in the upgrade, and reverses
this in the downgrade. However, downgrading is NOT safe if data exists:
- Naive DateTime values will be assigned the server's timezone when
  converting back to TIMESTAMP(timezone=True)
- This can cause incorrect timestamps if the original data was in a
  different timezone
- Data loss may occur for timestamps that were stored as naive DateTime

RECOMMENDATION:
- Only downgrade if the m_user table is empty
- If data exists, perform manual timezone normalization to UTC before
  downgrading, or accept potential data inconsistency
- The downgrade function includes a safety check to prevent automatic
  downgrade when user data exists

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb61f85c3622"
down_revision: str | Sequence[str] | None = "742d5bfb9e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "m_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("thumbnail_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["m_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_m_template_id"), "m_template", ["id"], unique=False)
    op.create_table(
        "t_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("rows_count", sa.Integer(), nullable=True),
        sa.Column("columns_count", sa.Integer(), nullable=True),
        sa.Column("sheets_count", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["m_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_t_file_id"), "t_file", ["id"], unique=False)
    op.create_index(op.f("ix_t_file_user_id"), "t_file", ["user_id"], unique=False)
    op.alter_column(
        "m_user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "m_user",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    WARNING: This downgrade is unsafe if user data exists!
    Converting naive DateTime back to timezone-aware TIMESTAMP will
    assign the server's timezone to existing timestamps, which may
    cause data inconsistency.

    This function checks if the m_user table has any rows and raises
    an error to prevent automatic downgrade with existing data.

    To force downgrade with data:
    1. Manually normalize all timestamps to UTC
    2. Comment out the safety check below
    3. Run the migration
    4. Verify timestamp correctness
    """
    # Safety check: Prevent downgrade if user data exists
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT COUNT(*) FROM m_user"))
    user_count = result.scalar()

    if user_count > 0:
        raise RuntimeError(
            f"Cannot safely downgrade: {user_count} users exist in m_user table. "
            "Downgrading with existing data may cause timestamp inconsistencies. "
            "See migration file docstring for manual downgrade instructions."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "m_user",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "m_user",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_t_file_user_id"), table_name="t_file")
    op.drop_index(op.f("ix_t_file_id"), table_name="t_file")
    op.drop_table("t_file")
    op.drop_index(op.f("ix_m_template_id"), table_name="m_template")
    op.drop_table("m_template")
    # ### end Alembic commands ###
